<?php
// Token-authorised image server for the mobile quiz API.
//
// Question-bank images (question text / answer options) cannot be served through the
// standard webservice/pluginfile.php route with a plain student token: question_pluginfile
// only authorises those files inside a quiz attempt/preview context, so it fails with
// "Course or activity not accessible". This endpoint authorises by web-service token +
// course enrolment instead, then streams the file from its question category context.
//
// Usage (URLs are generated by quiz_manager::local_file_url):
//   /local/academy/qfile.php?token=TOKEN&questionid=717&area=questiontext&itemid=717&file=image.png

require_once('../../config.php');
require_once($CFG->dirroot . '/webservice/lib.php');
require_once($CFG->libdir . '/filelib.php');

$token      = required_param('token', PARAM_RAW);
$questionid = required_param('questionid', PARAM_INT);
$area       = required_param('area', PARAM_ALPHANUMEXT);
$itemid     = required_param('itemid', PARAM_INT);
$filename   = required_param('file', PARAM_FILE);

// Only genuine question file areas may be served through here.
if (!in_array($area, ['questiontext', 'answer', 'generalfeedback'], true)) {
    send_file_not_found();
}

// ── Authenticate the web-service token → user ──
$api = new webservice();
try {
    $authresult = json_decode(json_encode($api->authenticate_user($token)), true);
    $userid = $authresult['user']['id'] ?? 0;
} catch (Exception $e) {
    $userid = 0;
}
if (empty($userid)) {
    header('HTTP/1.1 401 Unauthorized');
    die('Invalid token');
}

// ── Access check: admins see everything; otherwise the user must be enrolled in a
//    course that uses this question in a quiz. ──
$isadmin = has_capability('local/academy:manageplatform', context_system::instance(), $userid);
if (!$isadmin) {
    $courseids = $DB->get_fieldset_sql(
        "SELECT DISTINCT q.course
           FROM {quiz_slots} qs
           JOIN {quiz} q ON q.id = qs.quizid
          WHERE qs.questionid = :qid", ['qid' => $questionid]);

    $allowed = false;
    foreach ($courseids as $cid) {
        if (is_enrolled(context_course::instance($cid), $userid, '', true)) {
            $allowed = true;
            break;
        }
    }
    if (!$allowed) {
        header('HTTP/1.1 403 Forbidden');
        die('Not allowed');
    }
}

// ── Resolve the question category context where the files live, then stream the file. ──
$question = $DB->get_record('question', ['id' => $questionid], 'id, category', MUST_EXIST);
$category = $DB->get_record('question_categories', ['id' => $question->category], 'id, contextid', MUST_EXIST);

$fs   = get_file_storage();
$file = $fs->get_file($category->contextid, 'question', $area, $itemid, '/', $filename);
if (!$file || $file->is_directory()) {
    send_file_not_found();
}

send_stored_file($file, 86400, 0, false);
