<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

namespace theme_nit\local;

/**
 * Hook callbacks for theme_nit.
 *
 * @package    theme_nit
 * @copyright  2026 NIT
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class hook_callbacks {

    /**
     * Force a chrome-free ("embedded") page layout when a page is being viewed
     * inside the mobile app's in-app WebView.
     *
     * Why this exists
     * ---------------
     * The Flutter app renders most content natively, but some activities have no
     * native screen (forums, and generic mod/url, mod/page, mod/book, mod/lesson,
     * mod/scorm, etc.) so it opens the real Moodle page inside a WebView. In that
     * WebView the student must ONLY see the activity material — no site header,
     * footer, breadcrumbs, nav drawer, user/settings menu, activity prev/next,
     * "back to course" or login/logout links — nothing that lets them roam the
     * wider site or leave the activity.
     *
     * Moodle already ships exactly such a stripped layout: `embedded` (used for
     * iframes/filepickers). Switching the whole app WebView session to it gives us
     * chrome-free rendering server-side, so the app needs no CSS/JS injection.
     *
     * This runs on `before_http_headers`, which core dispatches at the very top of
     * core_renderer::header() BEFORE the page state moves to PRINTING_HEADER and
     * BEFORE the layout file is resolved — so set_pagelayout() here still takes
     * effect. Desktop/browser users are never affected: the detection below only
     * matches the app.
     *
     * Detection (any one is enough):
     *   1. `core_useragent::is_moodle_app()` — the WebView sends a User-Agent
     *      containing "MoodleMobile" (recommended; same signal the app already
     *      uses on its web-service calls). This is the cleanest single trigger.
     *   2. `?nitembed=1` on the URL — a fallback the app can append to the
     *      autologin `urltogo` target if it cannot change the WebView UA.
     *   3. A session flag we set on the first match — because in-activity links
     *      generated by core (e.g. a forum discussion, a reply form) carry
     *      neither signal, but they ARE loaded in the same isolated WebView
     *      session, so the flag keeps them chrome-free too.
     *
     * The session flag lives only in the WebView's own cookie jar / session, which
     * is separate from any desktop browser session, so it can never leak the
     * embedded layout to web users.
     *
     * @param \core\hook\output\before_http_headers $hook
     */
    public static function before_http_headers(\core\hook\output\before_http_headers $hook): void {
        global $PAGE, $SESSION;

        if (empty($PAGE)) {
            return;
        }

        // Never touch layouts that are already chrome-free or must not be altered.
        $skiplayouts = ['embedded', 'maintenance', 'redirect', 'print'];
        if (in_array($PAGE->pagelayout, $skiplayouts, true)) {
            return;
        }

        // Is this the app's WebView? Sticky for the rest of the (WebView-only) session.
        $isapp = !empty($SESSION->theme_nit_appembed)
            || \core_useragent::is_moodle_app()
            || (bool) optional_param('nitembed', 0, PARAM_BOOL);

        if (!$isapp) {
            return;
        }

        // Remember, so subsequent in-activity page loads stay chrome-free even
        // when they carry neither the app User-Agent nor the ?nitembed param.
        $SESSION->theme_nit_appembed = 1;

        $PAGE->set_pagelayout('embedded');
    }

    /**
     * Load the sign-up password affordances: a strength meter and a reveal
     * ("eye") toggle on the password box.
     *
     * Why a hook and not the template
     * -------------------------------
     * theme_nit already overrides core/signup_form_layout, but a Mustache
     * template cannot read $CFG. The meter has to know the site's *configured*
     * password policy (Site administration > Security > Site security settings)
     * so it never reports "strong" for something check_password_policy() will
     * reject on submit — the bar is an affordance, the server stays the gate.
     * So the policy and the labels are handed to the module from here.
     *
     * `before_footer_html_generation` is the right moment: the page is still
     * open, so js_call_amd() lands in the footer script block, and the password
     * box is guaranteed to be in the DOM by the time the module runs.
     *
     * Scoped to the sign-up page only. Nothing is injected anywhere else, and
     * with JS off the form degrades to exactly what core renders today.
     *
     * @param \core\hook\output\before_footer_html_generation $hook
     */
    public static function before_footer_html_generation(
        \core\hook\output\before_footer_html_generation $hook
    ): void {
        global $CFG, $PAGE;

        if (empty($PAGE) || $PAGE->pagetype !== 'login-signup') {
            return;
        }

        $policy = [
            // With the policy switched off there is no floor to clear, so the
            // meter scores purely on length and variety.
            'minlength'   => empty($CFG->passwordpolicy) ? 0 : (int) $CFG->minpasswordlength,
            'digits'      => empty($CFG->passwordpolicy) ? 0 : (int) $CFG->minpassworddigits,
            'lower'       => empty($CFG->passwordpolicy) ? 0 : (int) $CFG->minpasswordlower,
            'upper'       => empty($CFG->passwordpolicy) ? 0 : (int) $CFG->minpasswordupper,
            'nonalphanum' => empty($CFG->passwordpolicy) ? 0 : (int) $CFG->minpasswordnonalphanum,
        ];

        $strings = [
            'strength'     => get_string('passwordstrength', 'theme_nit'),
            'showpassword' => get_string('showpassword', 'theme_nit'),
            'hidepassword' => get_string('hidepassword', 'theme_nit'),
            // Keyed 1..4 to match the score the module produces.
            'levels'       => [
                1 => get_string('passwordstrengthweak', 'theme_nit'),
                2 => get_string('passwordstrengthfair', 'theme_nit'),
                3 => get_string('passwordstrengthgood', 'theme_nit'),
                4 => get_string('passwordstrengthstrong', 'theme_nit'),
            ],
        ];

        $PAGE->requires->js_call_amd('theme_nit/passwordstrength', 'init', [
            ['policy' => $policy, 'strings' => $strings],
        ]);
    }
}
